const background = [
  {
    eduCards: [
      {
        id: 0,
        title: "Virginia Tech",
        degree: "Bachelor of Science (BS), Electrical and Electronics Engineering",
        detail: "Graduated from Virginia Tech with a focus on Electrical and Electronics Engineering.",
        year: "2012 - 2016",
      },
    ],
  },
  {
    expCards: [
      {
        id: 0,
        title: "GEICO",
        role: "DevOps Architect",
        url: "https://www.geico.com/",
        desc: "As a DevOps Architect at GEICO, responsible for implementing Cluster API (CAPI), CAPZ, AKS, Argo CD, Helm, and Vault for optimizing deployment processes and ensuring scalable infrastructure.",
        year: "April 2024 - Present",
        location: "Maryland, United States",
      },
      {
        id: 1,
        title: "Intact",
        role: "Cyber Security Architect - AppSec",
        url: "https://www.intact.ca/",
        desc: "At Intact, served as a Cyber Security Architect specializing in AppSec, focusing on enhancing application security through tools like Palo Alto Networks Twistlock and Okta Single Sign-On.",
        year: "February 2024 - Present",
        location: "Toronto, Ontario, Canada",
      },
      {
        id: 2,
        title: "ReShell",
        role: "Partner",
        url: "https://www.reshell.com/",
        desc: "As a Partner at ReShell, involved in strategic planning and overseeing technological advancements in cloud architecture and DevOps practices.",
        year: "December 2023 - Present",
        location: "Toronto, Ontario, Canada",
      },
      {
        id: 3,
        title: "Box",
        role: "DevOps Architect",
        url: "https://www.box.com/",
        desc: "At Box, contributed as a DevOps Architect, focusing on enhancing deployment strategies using technologies like Kubernetes, Helm, and Argo CD.",
        year: "March 2024 - June 2024",
        location: "Redwood City, California, United States",
      },
      {
        id: 4,
        title: "Sleep Country Canada",
        role: "GCP Cloud Architect",
        url: "https://www.sleepcountry.ca/",
        desc: "Served as a GCP Cloud Architect at Sleep Country Canada, responsible for designing and implementing cloud solutions leveraging Google Cloud Platform technologies.",
        year: "January 2024 - February 2024",
        location: "Toronto, Ontario, Canada",
      },
      {
        id: 5,
        title: "PwC Canada",
        role: "Senior Manager 2",
        url: "https://www.pwc.com/ca/en.html",
        desc: "At PwC Canada, held the role of Senior Manager 2, overseeing technical projects involving Python, Vault, Terraform, Azure DevOps, AKS, and various client-specific technologies.",
        year: "May 2022 - February 2024",
        location: "Toronto, Ontario, Canada",
      },
      {
        id: 6,
        title: "CircleCI",
        role: "Senior DevOps Engineer",
        url: "https://circleci.com/",
        desc: "As a Senior DevOps Engineer at CircleCI, contributed to CI/CD pipelines using technologies like Javascript, Typescript, React, Redux, Kubernetes, AWS, and GCP.",
        year: "March 2021 - May 2022",
        location: "Remote",
      },
      {
        id: 7,
        title: "RocketBNK",
        role: "Senior DevOps Engineer",
        url: "https://www.rocketbnk.com/",
        desc: "At RocketBNK, responsible for managing CI/CD processes using AWS Codebuild, ECR, EKS, Terraform, Spinnaker, and administration of developer tooling like AWS MSK, Neo4j, and Datadog.",
        year: "August 2020 - March 2021",
        location: "Remote",
      },
      {
        id: 8,
        title: "Rogers Communications",
        role: "DevOps Engineer",
        url: "https://www.rogers.com/",
        desc: "As a DevOps Engineer at Rogers Communications, involved in managing deployments using Github, Terraform, Azure Devops, Ansible, Openshift, Azure API Gateway, AKS, Python, and other technologies.",
        year: "March 2020 - August 2020",
        location: "Greater Toronto Area Metropolitan Area",
      },
      {
        id: 9,
        title: "CIBC Capital Markets",
        role: "DevOps Engineer",
        url: "https://www.cibccm.com/",
        desc: "At CIBC Capital Markets, contributed to infrastructure management using AWS, GCP, Docker, Docker Swarm, Consul, Vault, Jenkins, Artifactory, Github, Nginx, AWS CloudFormation, and other cloud technologies.",
        year: "March 2019 - April 2020",
        location: "Toronto, Canada Area",
      },
      {
        id: 10,
        title: "PenFed Credit Union",
        role: "System Engineer - Cloud",
        url: "https://www.penfed.org/",
        desc: "At PenFed Credit Union, served as a System Engineer specializing in Cloud technologies, working on AWS implementations and cloud infrastructure management.",
        year: "October 2017 - February 2019",
        location: "Tysons, VA",
      },
      {
        id: 11,
        title: "ENQUIZIT INCORPORATED",
        role: "Cloud Engineer",
        url: "https://www.enquizit.com/",
        desc: "As a Cloud Engineer at ENQUIZIT INCORPORATED, involved in AWS cloud architecture and infrastructure management.",
        year: "June 2016 - October 2017",
        location: "Tysons",
      },
    ],
  },
];

export default function handler(req, res) {
  res.status(200).json(background);
}
