const portfolio = [
  {
    id: 0,
    projectName: "GEICO",
    url: "https://geico.com/",
    image: "projects/geico.png",
    projectDetail:
      "GEICO is a leading insurance company in the United States, providing auto, homeowners, renters, and motorcycle insurance.",
    technologiesUsed: [
      { tech: "Cluster API (CAPI)" },
      { tech: "CAPZ" },
      { tech: "AKS" },
      { tech: "Argo CD" },
      { tech: "Helm" },
      { tech: "Vault" },
    ],
    role: "DevOps Architect",
    year: "April 2024 - Present",
    location: "Maryland, United States",
  },
  {
    id: 1,
    projectName: "Intact",
    url: "https://intact.ca/",
    image: "projects/intact.png",
    projectDetail:
      "Intact Financial Corporation is the largest provider of property and casualty insurance in Canada and a leading provider of specialty insurance in North America.",
    technologiesUsed: [
      { tech: "ReShell" },
      { tech: "Partner" },
    ],
    role: "Cyber Security Architect - AppSec",
    year: "February 2024 - Present",
    location: "Toronto, Ontario, Canada",
  },
  {
    id: 2,
    projectName: "Box",
    url: "https://box.com/",
    image: "projects/box.png",
    projectDetail:
      "Box is a cloud content management and file sharing service for businesses.",
    technologiesUsed: [
      { tech: "DevOps Architect" },
      { tech: "AWS Lambda" },
      { tech: "Palo Alto Networks Twistlock" },
      { tech: "Okta Single Sign-On" },
    ],
    role: "DevOps Architect",
    year: "March 2024 - June 2024",
    location: "Redwood City, California, United States",
  },
  {
    id: 3,
    projectName: "Sleep Country Canada",
    url: "https://sleepcountry.ca/",
    image: "projects/sleepcountry.png",
    projectDetail:
      "Sleep Country Canada is Canada's leading specialty retailer of mattresses and sleep accessories.",
    technologiesUsed: [
      { tech: "GCP Cloud Architect" },
    ],
    role: "GCP Cloud Architect",
    year: "January 2024 - February 2024",
    location: "Canada",
  },
  {
    id: 4,
    projectName: "PwC Canada",
    url: "https://www.pwc.com/ca/",
    image: "projects/pwc.png",
    projectDetail:
      "PwC Canada is a leading professional services firm providing audit and assurance, consulting and deals, and tax services.",
    technologiesUsed: [
      { tech: "Senior Manager 2" },
      { tech: "Python" },
      { tech: "Vault" },
      { tech: "Terraform" },
      { tech: "Azure DevOps" },
      { tech: "AKS" },
    ],
    role: "Senior Manager 2",
    year: "May 2022 - February 2024",
    location: "Toronto, Ontario, Canada",
  },
  {
    id: 5,
    projectName: "CircleCI",
    url: "https://circleci.com/",
    image: "projects/circleci.png",
    projectDetail:
      "CircleCI is a leading continuous integration and continuous delivery (CI/CD) platform that automates the build, test, and deployment of applications.",
    technologiesUsed: [
      { tech: "Senior DevOps Engineer" },
      { tech: "JavaScript" },
      { tech: "TypeScript" },
      { tech: "React" },
      { tech: "Redux" },
      { tech: "Kubernetes" },
      { tech: "AWS" },
      { tech: "GCP" },
    ],
    role: "Senior DevOps Engineer",
    year: "March 2021 - May 2022",
    location: "United States",
  },
  {
    id: 6,
    projectName: "RocketBNK",
    url: "https://rocketbnk.com/",
    image: "projects/rocketbnk.png",
    projectDetail:
      "RocketBNK is a fintech company providing banking solutions through digital platforms.",
    technologiesUsed: [
      { tech: "Senior DevOps Engineer" },
      { tech: "AWS Codebuild" },
      { tech: "ECR" },
      { tech: "EKS" },
      { tech: "Terraform" },
      { tech: "Spinnaker" },
      { tech: "AWS MSK" },
      { tech: "Neo4j" },
      { tech: "Linux" },
      { tech: "Datadog" },
    ],
    role: "Senior DevOps Engineer",
    year: "August 2020 - March 2021",
    location: "Canada",
  },
  {
    id: 7,
    projectName: "Rogers Communications",
    url: "https://www.rogers.com/",
    image: "projects/ogers.png",
    projectDetail:
      "Rogers Communications is a leading Canadian telecommunications company providing wireless, cable TV, and internet services.",
    technologiesUsed: [
      { tech: "DevOps Engineer" },
      { tech: "GitHub" },
      { tech: "Terraform" },
      { tech: "Azure DevOps" },
      { tech: "Ansible" },
      { tech: "Openshift" },
      { tech: "Azure API Gateway" },
      { tech: "AKS" },
      { tech: "Python" },
    ],
    role: "DevOps Engineer",
    year: "March 2020 - August 2020",
    location: "Greater Toronto Area, Canada",
  },
  {
    id: 8,
    projectName: "CIBC Capital Markets",
    url: "https://www.cibc.com/en/about-cibc.html",
    image: "projects/cibc.png",
    projectDetail:
      "CIBC Capital Markets is a leading provider of financial services in Canada.",
    technologiesUsed: [
      { tech: "DevOps Engineer" },
      { tech: "AWS" },
      { tech: "GCP" },
      { tech: "Docker" },
      { tech: "Docker Swarm" },
      { tech: "Consul" },
      { tech: "Vault" },
      { tech: "Linux" },
      { tech: "Jenkins" },
      { tech: "Artifactory" },
      { tech: "GitHub" },
      { tech: "Nginx" },
      { tech: "AWS CloudFormation" },
      { tech: "AWS ECR" },
      { tech: "AWS LB" },
      { tech: "Autoscaling" },
      { tech: "EC2" },
      { tech: "S3" },
      { tech: "EBS" },
    ],
    role: "DevOps Engineer",
    year: "March 2019 - April 2020",
    location: "Toronto, Canada",
  },
  {
    id: 9,
    projectName: "PenFed Credit Union",
    url: "https://www.penfed.org/",
    image: "projects/penfed.png",
    projectDetail:
      "PenFed Credit Union is a credit union and financial services company serving members of the United States Armed Forces and defense-related employees.",
    technologiesUsed: [
      { tech: "System Engineer - Cloud" },
    ],
    role: "System Engineer - Cloud",
    year: "October 2017 - February 2019",
    location: "Tysons, VA",
  },
  {
    id: 10,
    projectName: "ENQUIZIT INCORPORATED",
    url: "https://enquizit.com/",
    image: "projects/enquizit.png",
    projectDetail:
      "ENQUIZIT INCORPORATED provides cloud solutions and IT consulting services.",
    technologiesUsed: [
      { tech: "Cloud Engineer" },
      { tech: "AWS Expert" },
    ],
    role: "Cloud Engineer",
    year: "June 2016 - October 2017",
    location: "Tysons, VA",
  },
  {
    id: 11,
    projectName: "Titan America",
    url: "https://titanamerica.com/",
    image: "projects/titanamerica.png",
    projectDetail:
      "Titan America is a leading environmentally and socially progressive heavy building materials company.",
    technologiesUsed: [
      { tech: "Electrical Engineering Intern" },
    ],
    role: "Electrical Engineering Intern",
    year: "June 2015 - August 2015",
    location: "United States",
  },
  {
    id: 12,
    projectName: "Siemens",
    url: "https://siemens.com/",
    image: "projects/siemens.png",
    projectDetail:
      "Siemens AG is a German multinational conglomerate company headquartered in Munich and the largest industrial manufacturing company in Europe.",
    technologiesUsed: [
      { tech: "Intern Engineer" },
    ],
    role: "Intern Engineer",
    year: "June 2014 - August 2014",
    location: "United States",
  },
];
export default function handler(req, res) {
  res.status(200).json(portfolio);
}
